### ISSUE TITLE
Please rename this repository "hc-backend"

### ISSUE THREAD

**Issue by roschaefer** [appinteractive/HC-Backend#2]
API is short for [Application programming interface](https://en.wikipedia.org/wiki/Application_programming_interface) and does **not** mean backend code. It could be anything. I hate, that I start to call the backend repository of our alpha "the API", which is just wrong.

As soon as we deploy the nitro version to staging and transfer this repository to @Human-Connection we should name it properly.

EDIT: Previously my favourite name was "server". After thinking about it, I think "backend" is better, because we are used to talk about "frontend" and "backend" developers.

**Comment by appinteractive** [comment]
Done
